CREATE SCHEMA IF NOT EXISTS PAGAMENTO_SERVICE;

CREATE SEQUENCE IF NOT EXISTS PAGAMENTO_SERVICE.SEQ_PAGAMENTO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

CREATE TABLE IF NOT EXISTS PAGAMENTO_SERVICE.PAGAMENTO (
    ID INTEGER NOT NULL DEFAULT NEXT VALUE FOR pagamento_service.seq_pagamento PRIMARY KEY,
    ID_PRENOTAZIONE INTEGER NOT NULL,
    ID_METODO_PAGAMENTO INTEGER NOT NULL,
    ID_STATO_PAGAMENTO INTEGER NOT NULL,
    IMPORTO_ANTICIPO DECIMAL(19, 2),
    IMPORTO_SALDO DECIMAL(19, 2) NOT NULL,
    DATA_ANTICIPO DATE,
    SCADENZA_SALDO DATE,
    CREDITO_RIMPORSATO DECIMAL(19, 2)
);

